name: gotmp
description: Help you to find your TMP
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  http: ^0.13.4
  lottie: ^1.2.1
  flutter_app_name: ^0.1.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo.png"
  remove_alpha_ios: true

flutter_app_name:
  name: "GoTMP"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/img/
    - assets/lottie/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
